module.exports = {
  plugins: ['@trivago/prettier-plugin-sort-imports'],
  semi: true,
  singleQuote: true,
  trailingComma: 'all',
  bracketSpacing: true,
  arrowParens: 'always',
  endOfLine: 'lf',
  jsxBracketSameLine: false,
  jsxSingleQuote: true,
  printWidth: 120,
  quoteProps: 'consistent',
  tabWidth: 2,
  importOrder: ['^react', '^@dtdot/(.*)$', '<THIRD_PARTY_MODULES>', '^[./]'],
  importOrderSeparation: true,
};
